---
- name: Test reachable hosts
  hosts: all
  gather_facts: false
  vars:
    connection_timeout: "10"
  tasks:
    - block:
      - ansible.builtin.wait_for_connection:
            timeout: "{{ connection_timeout }}"
            
      rescue:
        - ansible.builtin.meta: clear_host_errors
        - ansible.builtin.meta: end_host

    - ansible.builtin.add_host:
        name: '{{ item }}'
        groups: 'reachable'
      loop: "{{ ansible_play_hosts }}"
      run_once: true

    - ansible.builtin.debug:
        msg: "{{ groups['reachable'] }}"

- hosts: "{{ groups.reachable.0 }}"
  tasks:
    - ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"

    - name: latest Apache version installed
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: latest nginx version installed
      ansible.builtin.yum:
        name: nginx
        state: latest
        
    - name: latest mariadb version installed
      ansible.builtin.yum:
        name: mariadb
        state: latest
