---
- hosts: all
  vars:
    tmp_repo_directory: /tmp/csv_reports
    git_user_name: "Luis Cacho"
    git_email: "luiscachog@gmail.com"
    repo_url: https://{{ github_token }}@github.com/luiscachog/csv_reports.git
  tasks:
  - name: Clone a github repository
    ansible.builtin.git:
      repo: "{{ repo_url }}"
      dest: "{{ tmp_repo_directory }}"
      clone: yes
      update: yes
    delegate_to: localhost
    
  - name: Set fact for unreachable hosts
    ansible.builtin.set_fact:
      unreachable_hosts: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"
    run_once: true
    
  - name: Print unreachable hosts
    ansible.builtin.debug:
      var: unreachable_hosts
    when: unreachable_hosts is defined and unreachable_hosts | length > 0
    run_once: true

  - name: Write unreachable hosts to a file
    ansible.builtin.copy:
      content: "{{ unreachable_hosts | join('\n') }}"
      dest: "{{ tmp_repo_directory }}/results.txt"
      mode: '0644'
    delegate_to: localhost
    when: unreachable_hosts is defined and unreachable_hosts | length > 0
    run_once: true

  - name: Add new content to git repository
    ansible.builtin.shell: |
      git config --global user.name "{{ git_user_name }}"
      git config --global user.email "{{ git_email }}"
      git add -A && git commit -m "RHAAP Job ID {{ tower_job_id }}: Automated Commit by Ansible  " && git push
    args:
      chdir: "{{ tmp_repo_directory }}"
    ignore_errors: true
    register: output
    delegate_to: localhost
    run_once: true
    failed_when: >
      output.msg != "" and
      ("error" in output.msg or
      "conflict" in output.msg or
      "Errno" in output.msg or
      "fatal" in output.msg or
      (output.stdout != "" and
      "nothing to commit, working tree clean" not in output.stdout) or
      (output.stderr != ""))
